version: "3.9"

# when running test local, you can specify the image version using the env var DYNAMODB_VERSION.
# Example: DYNAMODB_VERSION=1.18.0 make

services:
  dynamodb:
    image: amazon/dynamodb-local:${DYNAMODB_VERSION:-1.18.0}
    container_name: dynamodb
    healthcheck:
      test: curl localhost:8000
    ports:
      - "8000:8000"
